stages:
  - docker-build

variables:
  DOCKER_IMAGE_VERSIONED: $CI_REGISTRY_IMAGE/maven-docker:${CI_COMMIT_SHORT_SHA}

docker-build-maven-image:
  stage: docker-build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY"
  script:
    - docker build -t "$DOCKER_IMAGE_VERSIONED" .
    - docker push "$DOCKER_IMAGE_VERSIONED"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "master"'
      changes:
        - Dockerfile
        - .gitlab-ci-docker-build.yml
    - when: manual