stages:
  - build

variables:
  IMAGE_NAME: "java21-docker-azcli"
  IMAGE_TAG: "$CI_COMMIT_SHA"
  DOCKER_BUILDKIT: "1"

build-and-push-docker-image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "$ARM_CLIENT_SECRET" | docker login $AZURE_REGISTRY_NAME -u "$ARM_CLIENT_ID" --password-stdin
  script:
    - >
      docker build \
        --cache-from "$AZURE_REGISTRY_NAME/$IMAGE_NAME:latest" \
        --build-arg BUILDKIT_INLINE_CACHE=1 \
        -t "$AZURE_REGISTRY_NAME/$IMAGE_NAME:$IMAGE_TAG" \
        .
    - docker push "$AZURE_REGISTRY_NAME/$IMAGE_NAME:$IMAGE_TAG"
    - >
      if [ "$CI_COMMIT_BRANCH" = "main" ]; then
        docker tag "$AZURE_REGISTRY_NAME/$IMAGE_NAME:$IMAGE_TAG" "$AZURE_REGISTRY_NAME/$IMAGE_NAME:latest"
        docker push "$AZURE_REGISTRY_NAME/$IMAGE_NAME:latest"
      fi
  rules:
    - when: manual
    - allow_failure: false
    - exists:
        - Dockerfile
